// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBncVGyNi2f0M8cZHUI2Pwqw111qlw6ckM',
    appId: '1:604717802298:web:d109238aadf327b96fa603',
    messagingSenderId: '604717802298',
    projectId: 'nexora-it-31453',
    authDomain: 'nexora-it-31453.firebaseapp.com',
    databaseURL: 'https://nexora-it-31453-default-rtdb.firebaseio.com',
    storageBucket: 'nexora-it-31453.firebasestorage.app',
    measurementId: 'G-2KT3MS1ER6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBvifqHeOAK_sBLLoMTycyVNLCnSq4Jn98',
    appId: '1:604717802298:android:3b867f55758092926fa603',
    messagingSenderId: '604717802298',
    projectId: 'nexora-it-31453',
    databaseURL: 'https://nexora-it-31453-default-rtdb.firebaseio.com',
    storageBucket: 'nexora-it-31453.firebasestorage.app',
  );
}
